spring:
  application:
    name: Home-Rental-APP
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/se
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 8080